### ISSUE TITLE
Fos classification

### ISSUE THREAD

**Issue by carmanzhang** [lin-ao/enhancing_the_makg#1]
Hi Ao,
  Very interesting paper, these enhancements such as author name disambiguation and paper classification will definitely benefit MAKG. In these enhancements, I am particularly interested in FOS classification, and we have verified that your FoS is more accurate than the original MAG FoS.
Currently, we try to use the enhanced FOS for our applications, but we found that only one FOS could be obtained for each MAKG paper, this puts us in a dilemma. We do not have sufficient computational resources to handle a huge dataset like MAKG. I am wondering if it is possible to access your pre-trained model (SciBERT) for FoS classification.

**Comment by lin-ao** [comment]
Hi, the exact fine-tuned model I used is not available unfortunately. But SciBERT is a pre-trained model which you can access [here](https://github.com/allenai/scibert). The fine-tuning part is actually not very resource intensive, you can easily scale down by using less training data as well. You can use it with [Hugging Face](https://github.com/huggingface/transformers) or in my case, I used a package called [Simple Transformers](https://simpletransformers.ai/) which can be used as a sort of interface to easily implement models from Hugging Face as well.
In order to generate the training data you don't actually need the entirety of the MAKG, just some specific files (PaperAbstractsInvertedIndex.txt, FieldsOfStudy.txt, FieldOfStudyChildren.txt, or Journals.txt); you can download them individually from [here](https://makg.org/rdf-dumps/). This was also a while ago for me so I don't remember the exact details, but I was also running into resource issues due to the large file sizes. One way of dealing with it was just manually splitting the file into parts, running the processing step on each part individually and then manually aggregate the results.

**Comment by carmanzhang** [comment]
Thank you so much, @lin-ao.
By the way, does the enhanced FoS only start from the 2020-06-19 version of MAKG (on Zenodo)?

**Comment by lin-ao** [comment]
Yes, that was the version I used when working on this.
